### ISSUE TITLE
Cannot run from source.

### ISSUE THREAD

**Issue by vivandoshi08** [pquiring/jfcraft#1]
When I try to build the game, the jfcraft-client.exe isn't created, so I can't run from source.

**Comment by pquiring** [comment]
ant executable
That will generate the exe files.

**Comment by pquiring** [comment]
ant msi
This will generate the exe files and msi package for installation.

**Comment by pquiring** [comment]
Please note you must have compiled the native launchers in JavaForce first which requires VisualC++ in your path.
See Javaforce documentation on native launchers and native library : https://github.com/pquiring/javaforce
Thanks

**Comment by vivandoshi08** [comment]
I don't really understand what you mean in the last comment. I run the compiling inside the developer command line for visual studio 2019 if that helps. Also I still can't run the jfcraft-client.exe; instead, I get this error.
![Screenshot (31)](https://user-images.githubusercontent.com/41412103/102816705-4efe5680-4383-11eb-89b6-2da2f48813ff.png)
Also when building the exe, I get this error
![Screenshot (30)](https://user-images.githubusercontent.com/41412103/102816735-5a518200-4383-11eb-9be2-a5ccaa8bfdf5.png)

**Comment by pquiring** [comment]
cd javaforce
cd stubs\windows
ant
cd javaforce
cd native\windows
ant

That will build the native launchers and native library for Windows.  Then you can build the executables for the game.

**Comment by pquiring** [comment]
I've just added some ant tasks to JavaForce to download pre-built native binaries.  You could follow these steps:

cd javaforce
git pull
cd stubs\windows
ant get-bin
cd javaforce
cd native\windows
ant get-bin

Just in case you have problems building the native files.  They have a lot of dependancies which are sometimes difficult to setup on Windows.

Thanks,

**Comment by vivandoshi08** [comment]
Thank you for the feedback. Now, the native library errors are fixed, yet there is still an error in building the executable, which is "java.io.FileNotFoundException: jfcraft-client.cfg (The system cannot find the file specified)"

**Comment by pquiring** [comment]
Opps, I was missing those files in the repo.  Do a "git pull" and you should have them now.

**Comment by vivandoshi08** [comment]
All the building work great now, but when I try to run the exe, I get this error, "Unrecognized VM option 'UseZGC' ". I am also using openjdk 15 if that helps

**Comment by vivandoshi08** [comment]
I also tried with openjdk 14, but it still had the same error

**Comment by pquiring** [comment]
UseZGC is only supported on JDK15.  You should be using latest JDK.

**Comment by pquiring** [comment]
You said you tried JDK15, that should work.  What JDK vendor are you using?  
Oracle or AdoptOpenJDK should work fine.
OpenJ9 would not be supported.

**Comment by vivandoshi08** [comment]
I have tried both oracle and adoptopenjdk 15, yet it still didn't work.

**Comment by pquiring** [comment]
What version of Windows are you running?  Need the build #
ie: Version 10.0.19042.685

**Comment by vivandoshi08** [comment]
Windows 10
Year 2004
Build 19041.630

**Comment by pquiring** [comment]
What about your registry, do you have another older JRE installed?
What is the value of CurrentVersion under HKEY_LOCAL_MACHINE\SOFTWARE\JavaSoft\Java Runtime Environment

**Comment by vivandoshi08** [comment]
The value of the currentversion is 1.8

**Comment by vivandoshi08** [comment]
Do I need jre 15 in Java Runtime Environment for this to work?

**Comment by vivandoshi08** [comment]
Do i have to change the version to 1.15

**Comment by vivandoshi08** [comment]
is there a different version i need for the jre

**Comment by pquiring** [comment]
The launcher is using JRE 8 that is found in your registry.
I would download JRE 15 from AdoptOpenJDK.net
Click on "other platforms" and select JRE 15 MSI for Win64.
Make sure to select "JavaSoft (Oracle) registry keys" during installation.

**Comment by vivandoshi08** [comment]
thank you. It finally builds now.
